-- CreateEnum
CREATE TYPE "StratSection" AS ENUM ('LINEUPS_AND_ABILITY_TRICKS_ATTACKER_SIDE', 'LINEUPS_AND_ABILITY_TRICKS_DEFENDER_SIDE', 'EARLY_ROUND_ATTACKER_SIDE', 'EARLY_ROUND_DEFENDER_SIDE', 'MID_ROUND_ATTACKER_SIDE', 'MID_ROUND_DEFENDER_SIDE', 'LATE_ROUND_ATTACKER_SIDE', 'LATE_ROUND_DEFENDER_SIDE', 'MISC');

-- CreateTable
CREATE TABLE "StratImage" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "deletedAt" TIMESTAMP(3),
    "stratId" TEXT NOT NULL,
    "imageURL" TEXT NOT NULL,
    "stratSection" "StratSection" NOT NULL DEFAULT 'MISC',

    CONSTRAINT "StratImage_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "StratImage" ADD CONSTRAINT "StratImage_stratId_fkey" FOREIGN KEY ("stratId") REFERENCES "Strat"("id") ON DELETE CASCADE ON UPDATE CASCADE;
